title: MAGENTA INVICTUS
description: A Magento 2-focused page created by the Magenta team
copyright: Magenta
author: Magenta
author_profile_link: https://github.com/magentainvictus2024/magentainvictus2024/
show_github: false
show_downloads: false
google_analytics:
theme: jekyll-theme-architect